version: '3.8'

# TradingAgents-CN v1.0.0-preview Docker Compose配置
# 使用Docker Hub镜像
#
# 使用方法：
# 1. 复制.env.example为.env并配置环境变量
# 2. 运行: docker-compose -f docker-compose.hub.yml up -d
# 3. 访问: http://localhost:3000 (前端) 和 http://localhost:8000 (后端API)

services:
  # MongoDB数据库
  mongodb:
    image: mongo:4.4
    container_name: tradingagents-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - tradingagents_mongodb_data_v1:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: tradingagents123
      MONGO_INITDB_DATABASE: tradingagents
      TZ: "Asia/Shanghai"
    networks:
      - tradingagents-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: tradingagents-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - tradingagents_redis_data_v1:/data
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - tradingagents-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # FastAPI后端服务
  backend:
    # 替换为你的Docker Hub用户名
    image: hsliup/tradingagents-backend:latest
    container_name: tradingagents-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      TZ: "Asia/Shanghai"
      # MongoDB配置（Docker环境，带认证）
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"
      MONGODB_USERNAME: "admin"
      MONGODB_PASSWORD: "tradingagents123"
      MONGODB_DATABASE: "tradingagents"
      MONGODB_AUTH_SOURCE: "admin"
      MONGODB_URL: "mongodb://admin:tradingagents123@mongodb:27017/tradingagents?authSource=admin"
      # Redis配置
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_URL: "redis://redis:6379/0"
      DOCKER_CONTAINER: "true"
      # CORS配置
      CORS_ORIGINS: "http://localhost:3000,http://localhost:8080,http://localhost:5173"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tradingagents-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Vue 3前端服务
  frontend:
    # 替换为你的Docker Hub用户名
    image: hsliup/tradingagents-frontend:latest
    container_name: tradingagents-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Shanghai"
      VITE_API_BASE_URL: "http://localhost:8000"
    depends_on:
      - backend
    networks:
      - tradingagents-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  tradingagents_mongodb_data_v1:
  tradingagents_redis_data_v1:

networks:
  tradingagents-network:
    driver: bridge

